---
title: "Lab_Exercise_2_Obas"
author: "Barbie Joy Obas"
date: "2024-02-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product1 <- data.frame()

for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/ETUDE-Darling-Water-Lipstick-Cherry/product-reviews/B099RYFLSW/ref=cm_cr_arp_d_paging_btm_next", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
 
  productName <- "ETUDE Dear Darling Water Tint Lipstick 9.5 g, 02 Cherry Ade"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product1 <- rbind(product1, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product1)
```

```{r}

product2 <- data.frame()

for (page in 1:5) {
  link2 <- paste0("https://www.amazon.com.au/ROMAND-Juicy-lasting-Colors-ALMOND/product-reviews/B08MT5KZ9W/ref=cm_cr_arp_d_paging_btm_next", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session2 <- bow(link2, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session2) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
 
  productName <- "Romand Fruits Series Juicy Lasting Lip Tint 5.5 g, 19 Almond Rose"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product2 <- rbind(product2, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product2)
```

```{r}

product3 <- data.frame()

for (page in 1:5) {
  link3 <- paste0("https://www.amazon.com.au/NYX-PROFESSIONAL-Hydration-Non-sticky-Formula/product-reviews/B0BL8HXJMX/ref=cm_cr_arp_d_paging_btm_next", page)
  session3 <- bow(link3, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session3) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
 
  productName <- "NYX PROFESSIONAL MAKEUP, Fat Oil, Lip drip, 12HR Hydration, Non-sticky Formula"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product3 <- rbind(product3, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product3)
```


```{r}

product4 <- data.frame()

for (page in 1:5) {
  link4 <- paste0("https://www.amazon.com.au/Darling-High-Color-Minerals-Vitamins-Moisture/product-reviews/B099RWBNF4/ref=cm_cr_arp_d_paging_btm_next", page)
  session4 <- bow(link3, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session3) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
 
  productName <- "ETUDE Dear Darling Water Gel Tint Ice Cream"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product4 <- rbind(product4, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product4)
```


```{r}

product5 <- data.frame()

for (page in 1:5) {
  link5 <- paste0("https://www.amazon.com.au/Rom-Dewyful-Water-Salty-Peach/product-reviews/B09HZJJ9NP/ref=cm_cr_arp_d_paging_btm_next_", page)
  session5 <- bow(link3, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session5) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
 
  productName <- "Rom&nd Dewyful Water Tint 5 g, 02 Salty Peach"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product5 <- rbind(product5, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product5)
```

```{r}

product6 <- data.frame()

for (page in 1:5) {
  link6 <- paste0("https://www.amazon.com.au/Darling-High-Color-Minerals-Vitamins-Moisture/product-reviews/B099RWBNF4/ref=cm_cr_arp_d_paging_btm_next_", page)
  session6 <- bow(link6, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session3) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
 
  productName <- "ETUDE Dear Darling Water Gel Tint Ice Cream"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product6 <- rbind(product6, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product6)
```

```{r}

product7 <- data.frame()

for (page in 1:5) {
  link7 <- paste0("https://www.amazon.com.au/Romand-Dewyful-Water-No-12-Canyon/product-reviews/B0BGKPZFKQ/ref=cm_cr_arp_d_paging_btm_next", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session7 <- bow(link7, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session7) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
 
  productName <- "Romand Dewyful Water Lip Tint 5 g, No.12 Canyon"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product7 <- rbind(product7, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product7)
```


```{r}

product8 <- data.frame()

for (page in 1:5) {
  link8 <- paste0("https://www.amazon.com.au/KIKO-Milano-Lipstick-Transfer-Extremely/product-reviews/B078HBNMWJ/ref=cm_cr_arp_d_paging_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session8 <- bow(link8, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session8) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
 
  productName <- "KIKO Milano Long Lasting Colour Lip Marker 106t"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product8 <- rbind(product8, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product8)
```

```{r}

product9 <- data.frame()

for (page in 1:5) {
  link9 <- paste0("https://www.amazon.com.au/ETUDE-HOUSE-Dear-Darling-Tint/product-reviews/B09BF6VR95/ref=cm_cr_arp_d_paging_btm_next", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session9 <- bow(link9, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session9) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
 
  productName <- "ETUDE Dear Darling Water Gel Lip Tint Lipstick"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product9 <- rbind(product9, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product9)
```


```{r}

product10 <- data.frame()

for (page in 1:5) {
  link10 <- paste0("https://www.amazon.com.au/Revlon-Kiss-Cushion-4-4ml-CORAL/product-reviews/B07DC7J2FJ/ref=cm_cr_arp_d_paging_btm_next", page)
  session10 <- bow(link10, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session10) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }
 
  productName <- "Revlon Kiss Cushion Lip Tint 4.4ml 250 HIGH END CORAL"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product10 <- rbind(product10, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product10)
```

```{r}

product11 <- data.frame()

for (page in 1:5) {
  link11 <- paste0("https://www.amazon.com.au/NYX-PROFESSIONAL-MAKEUP-Smooth-Lipstick/product-reviews/B0BGYCKQ2G/ref=cm_cr_arp_d_paging_btm_next", page)
  session11 <- bow(link11, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session11) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "NYX PROFESSIONAL MAKEUP Smooth Whip Matte Lip Cream"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product11 <- rbind(product11, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product11)

```


```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product12 <- data.frame()

for (page in 1:5) {
  link12 <- paste0("https://www.amazon.com.au/Revlon-Kiss-Sweet-Cherry-Grams/product-reviews/B01N28GOZ1/ref=cm_cr_arp_d_paging_btm_next", page)
  session12 <- bow(link12, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session12) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Revlon Kiss™ Balm, Sweet Cherry, 2.6g"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product12 <- rbind(product12, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product12)

```


```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product13 <- data.frame()

for (page in 1:5) {
  link13 <- paste0("https://www.amazon.com.au/Burts-Bees-Fig-Shimmer-2-6g/product-reviews/B0018QKL7W/ref=cm_cr_arp_d_paging_btm_next", page)
  session13 <- bow(link13, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session13) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Burt's Bees 100% Natural Moisturizing Lip Shimmer"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product13 <- rbind(product13, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product13)

```


```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product14 <- data.frame()

for (page in 1:5) {
  link14 <- paste0("https://www.amazon.com.au/Maybelline-Lifter-Gloss-Hydrating-Lip/product-reviews/B082XRRPK9/ref=cm_cr_arp_d_paging_btm_next", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session14 <- bow(link14, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session14) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Maybelline New York Hydrating Lip Gloss - Silk"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product14 <- rbind(product14, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product14)

```


```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product15 <- data.frame()

for (page in 1:5) {
  link15 <- paste0("https://www.amazon.com.au/l-f-Hydrating-Core-Shine-Happy/product-reviews/B09486XPSK/ref=cm_cr_arp_d_paging_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session15 <- bow(link15, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session15) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "e.l.f. Hydrating Core Lip Shine, Happy"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product15 <- rbind(product15, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product15)

```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product16 <- data.frame()

for (page in 1:5) {
  link16 <- paste0("https://www.amazon.com.au/Maybelline-Lifter-Gloss-Hydrating-Lip/product-reviews/B08XXSYKL1/ref=cm_cr_arp_d_paging_btm_next", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session16 <- bow(link16, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session16) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Maybelline New York Hydrating Lip Gloss - Topaz"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product16 <- rbind(product16, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product16)

```


```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product17 <- data.frame()

for (page in 1:5) {
  link17 <- paste0("https://www.amazon.com.au/Ink-The-Velvet-4g-New/product-reviews/B07V1C9FLT/ref=cm_cr_arp_d_paging_btm_next", page)
  session17 <- bow(link17, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session17) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Peripera Ink Velvet #3 Red Only, 4 g"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product17 <- rbind(product17, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product17)


```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product18 <- data.frame()

for (page in 1:5) {
  link18 <- paste0("https://www.amazon.com.au/Maybelline-New-York-Superstay-Longwear/product-reviews/B09NQH1P4S/ref=cm_cr_arp_d_paging_btm_next", page)
  session18 <- bow(link18, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session18) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Maybelline New York Superstay Vinyl Ink Longwear Liquid Lipstick in Coy"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product18 <- rbind(product18, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product18)

```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product19 <- data.frame()

for (page in 1:5) {
  link19 <- paste0("https://www.amazon.com.au/MOONSHOT-Performance-Blur-Fixing-Tint/product-reviews/B0B5QMNH2V/ref=cm_cr_arp_d_paging_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session19 <- bow(link19, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session19) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "MOONSHOT Performance Blur Fixing Tint"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product19 <- rbind(product19, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product19)

```


```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product20 <- data.frame()

for (page in 1:5) {
  link20 <- paste0("https://www.amazon.com.au/l-f-Monochromatic-Luxuriously-Blendable-Glimmering/product-reviews/B088WHRL2L/ref=cm_cr_arp_d_paging_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session20 <- bow(link20, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session20) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "e.l.f. Monochromatic Multi Stick"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product20 <- rbind(product20, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product20)

```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product21 <- data.frame()

for (page in 1:5) {
  link21 <- paste0("https://www.amazon.com.au/Ink-The-Velvet-4g-New/product-reviews/B07V1C9FLT/ref=cm_cr_arp_d_paging_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session21 <- bow(link21, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session21) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Peripera Ink Velvet #3 Red Only, 4 g"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product21 <- rbind(product21, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product21)

```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product22 <- data.frame()

for (page in 1:5) {
  link22 <- paste0("https://www.amazon.com.au/Mineral-Fusion-MF4010-Lipstick-Alluring/product-reviews/B002LA3SWO/ref=cm_cr_arp_d_paging_btm_next", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session22 <- bow(link22, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session22) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Mineral Fusion Lipstick, Alluring"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product22 <- rbind(product22, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product22)

```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product23 <- data.frame()

for (page in 1:5) {
  link23 <- paste0("https://www.amazon.com.au/Jane-Iredale-Kissed-Cheek-Stain/product-reviews/B004SGZ610/ref=cm_cr_arp_d_paging_btm_next", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session23 <- bow(link23, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session23) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Jane Iredale Just Kissed Lip Stain, Forever Pink"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product23 <- rbind(product23, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product23)

```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product24 <- data.frame()

for (page in 1:5) {
  link24 <- paste0("https://www.amazon.com.au/Lipstick-Hydrating-Moisturizing-Application-Perfectly/product-reviews/B09F6CSK7W/ref=cm_cr_arp_d_paging_btm_next", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session24 <- bow(link24, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session24) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Lipstick Hydrating Moisturizing Application Perfectly"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product24 <- rbind(product24, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product24)

```


```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product25 <- data.frame()

for (page in 1:5) {
  link25 <- paste0("https://www.amazon.com.au/LOr%C3%A9al-Paris-Intense-Lipstick-AVANT-GARDE/product-reviews/B08P5DHQL9/ref=cm_cr_arp_d_paging_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session25 <- bow(link25, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session25) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "L'Oreal Paris Color Riche Intense Volume"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product25 <- rbind(product25, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product25)

```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product26 <- data.frame()

for (page in 1:5) {
  link26 <- paste0("https://www.amazon.com.au/NYX-Soft-Matte-Cream-paulo/product-reviews/B004LXKVPQ/ref=cm_cr_arp_d_paging_btm_next_2", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session26 <- bow(link26, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session26) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "NYX Professional Makeup Soft Matte Lip Cream"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product26 <- rbind(product26, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product26)

```


```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product27 <- data.frame()

for (page in 1:5) {
  link27 <- paste0("https://www.amazon.com.au/Revlon-Ultra-Matte-Lipcolor-Kisses/product-reviews/B01FKL4J64/ref=cm_cr_arp_d_paging_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session27<- bow(link27, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session27) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Revlon Ultra HD Matte Lipcolor, HD Kisses"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product27 <- rbind(product27, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product27)

```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product28 <- data.frame()

for (page in 1:5) {
  link28 <- paste0("https://www.amazon.com.au/C-Bigelow-Mentha-Shimmer/product-reviews/B01C3GRX5S/ref=cm_cr_arp_d_paging_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session28<- bow(link28, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session28) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Bath & Body Works C.O. Bigelow 3 Pack Mentha Shimmer"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product28 <- rbind(product28, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product28)

```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product29 <- data.frame()

for (page in 1:5) {
  link29 <- paste0("https://www.amazon.com.au/Revlon-Super-Lustrous-Lipstick-Blushed/product-reviews/B000YDMO7U/ref=cm_cr_arp_d_paging_btm_nex_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session29<- bow(link29, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session29) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Revlon Super Lustrous Lipstick, Blushed"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product29 <- rbind(product29, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product29)

```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product30 <- data.frame()

for (page in 1:5) {
  link30 <- paste0("https://www.amazon.com.au/Nicole-Miller-Collection-Shimmery-Glosses/product-reviews/B07YBHWVR1/ref=cm_cr_arp_d_paging_btm_next", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session30<- bow(link30, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session30) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Nicole Miller 10 Pc Lip Gloss Collection"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product30 <- rbind(product30, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product30)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product31 <- data.frame()

for (page in 1:5) {
  link31 <- paste0("https://www.amazon.com.au/BIGELOW-Shimmer-Bath-Body-Works/product-reviews/B00AGQU3U0/ref=cm_cr_arp_d_paging_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session31<- bow(link31, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session31) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "BIGELOW Shimmer Bath Body Works/"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product31 <- rbind(product31, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product31)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product32 <- data.frame()

for (page in 1:5) {
  link32 <- paste0("https://www.amazon.com.au/Manhattan-Intensive-Shimmer-Finish-Colour/product-reviews/B00HN1CQSS/ref=cm_cr_arp_d_paging_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session32<- bow(link32, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session32) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Manhattan Intensive Shimmer Finish Colour"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product32 <- rbind(product32, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product32)
```


```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product33 <- data.frame()

for (page in 1:5) {
  link33 <- paste0("https://www.amazon.com.au/Revlon-Lustrous-Lipstick-Abstract-Orange/product-reviews/B005QZXK38/ref=cm_cr_arp_d_paging_btm_next", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session33<- bow(link33, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session33) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Revlon Lipstick, Super Lustrous Lipstick"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product33<- rbind(product33, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product33)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product34 <- data.frame()

for (page in 1:5) {
  link34 <- paste0("https://www.amazon.com.au/NYX-PROFESSIONAL-MAKEUP-Butter-Gloss/product-reviews/B00ICTZ3YE/ref=cm_cr_arp_d_paging_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session34<- bow(link34, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session34) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "NYX Professional Makeup Butter Gloss, Angel Food Cake"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product34<- rbind(product34, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product34)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product35 <- data.frame()

for (page in 1:5) {
  link35 <- paste0("https://www.amazon.com.au/Revlon-Super-Lustrous-Lipstick-Moisturizing/product-reviews/B07XVV9HYT/ref=cm_cr_arp_d_paging_btm_nex", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session35<- bow(link35, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session35) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Revlon Super Lustrous Glass Shine Lipstick,"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product35<- rbind(product35, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product35)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product36 <- data.frame()

for (page in 1:5) {
  link36 <- paste0("https://www.amazon.com.au/Collection-Shimmery-Glosses-Lasting-Birthday/product-reviews/B081TFMPSP/ref=cm_cr_arp_d_paging_btm_next", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session36<- bow(link36, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session36) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Enchante Ellen Tracy 10 Pc Lip Gloss Collection"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product36<- rbind(product36, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product36)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product37 <- data.frame()

for (page in 1:5) {
  link37 <- paste0("https://www.amazon.com.au/Canyon-Rose-Full-Coverage-Lipstick-Moisturiser/product-reviews/B08W8KMSVC/ref=cm_cr_arp_d_paging_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session37<- bow(link37, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session37) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "(Canyon Rose) - Julep It's Balm Lip Balm Crayon"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product37<- rbind(product37, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product37)
```


```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product38 <- data.frame()

for (page in 1:5) {
  link38 <- paste0("https://www.amazon.com.au/Rimmel-Provocalips-16Hr-Proof-Colour/product-reviews/B00MGK9ZTO/ref=cm_cr_arp_d_paging_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session38<- bow(link38, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session38) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Rimmel London Provocalips 16HR Kiss Proof Lip Colour"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product38<- rbind(product38, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product38)
```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product39 <- data.frame()

for (page in 1:5) {
  link39 <- paste0("https://www.amazon.com.au/5ml-Manila-PROFESSIONAL-MAKEUP-Metallic/product-reviews/B07C92WY9R/ref=cm_cr_arp_d_paging_btm_next", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session39 <- bow(link39, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session39) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "NYX PROFESSIONAL MAKEUP Soft Matte Metallic Lip Cream"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product39<- rbind(product39, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product39)

```


```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product40 <- data.frame()

for (page in 1:5) {
  link40 <- paste0("https://www.amazon.com.au/Ludicrous-Crayon-Lovesick-Cream-Matte/product-reviews/B089NL4XXB/ref=cm_cr_arp_d_paging_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session40 <- bow(link40, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session40) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Milani Ludicrous Matte Lip Crayon 150, Lovesick, 1.4 g"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product40 <- rbind(product40, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product40)
```


```{r}


library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product41 <- data.frame()

for (page in 1:5) {
  link41 <- paste0("https://www.amazon.com.au/Lipstick-270-Pigmented-Intense-Fragrance/product-reviews/B08XXQXXHG/ref=cm_cr_arp_d_paging_btm_next", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session41 <- bow(link41, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session41) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "3INA MAKEUP - The Lipstick 270 - Dark Red Matte Lipstick"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product41 <- rbind(product41, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product41)

```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product42 <- data.frame()

for (page in 1:5) {
  link42 <- paste0("https://www.amazon.com.au/Lipsticks-Hydrating-Cruelty-Free-Full-Coverage-Cosmopolis/product-reviews/B08H2FLW4Q/ref=cm_cr_arp_d_paging_btm_next", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session42 <- bow(link42, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session42) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "OULAC Pink Metallic Shine Lipstick, Baby Pink Glitter Long Lasting"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product42 <- rbind(product42, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product42)

```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product43 <- data.frame()

for (page in 1:5) {
  link43 <- paste0("https://www.amazon.com.au/RIMMEL-LONDON-Matte-Liquid-Colour/product-reviews/B0711TZHGP/ref=cm_cr_arp_d_paging_btm_nex", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session43 <- bow(link43, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session43) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Rimmel Stay Matte Lip Liquid, Pink Blink, 0.21 Fluid Ounce"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product43 <- rbind(product43, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product43)

```


```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product44 <- data.frame()

for (page in 1:5) {
  link44 <- paste0("https://www.amazon.com.au/Clinique-Pop-Splash-Gloss-Hydration/product-reviews/B079229D8K/ref=cm_cr_arp_d_paging_btm_nex_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session44 <- bow(link44, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session44) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Clinique Pop Splash - 19 Vino Pop By Clinique for Women"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product44 <- rbind(product44, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product44)

```

```{r}


library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product45 <- data.frame()

for (page in 1:5) {
  link45 <- paste0("https://www.amazon.com.au/Lime-Crime-Cherry-CHERRY-Non-Sticky/product-reviews/B07NR2KX3X/ref=cm_cr_arp_d_paging_btm_next", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session45 <- bow(link45, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session45) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Lime Crime Wet Cherry Lip Gloss (SWEET CHERRY)"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product45 <- rbind(product45, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product45)

```


```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product46 <- data.frame()

for (page in 1:5) {
  link46 <- paste0("https://www.amazon.com.au/5ml-Rose-Honest-Beauty-Kissable/product-reviews/B07F44SCSQ/ref=cm_cr_arp_d_paging_btm_next", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session46 <- bow(link46, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session46) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Honest Lip Crayon Lush Sheer - Rose Women Lipstick"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product46 <- rbind(product46, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product46)


```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product47 <- data.frame()

for (page in 1:5) {
  link47 <- paste0("https://www.amazon.com.au/Rimmel-Glossy-Lipgloss-Fluid-Seduction/product-reviews/B0058CPDN4/ref=cm_cr_dp_d_show_all_btm", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session47 <- bow(link47, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session47) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Rimmel Stay Glossy Lipgloss"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product47 <- rbind(product47, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product47)

```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product48 <- data.frame()

for (page in 1:5) {
  link48 <- paste0("https://www.amazon.com.au/Physicians-Formula-Diamond-Plumper/product-reviews/B08RRY5PF2/ref=cm_cr_dp_d_show_all_btm", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session48 <- bow(link48, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session48) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Physicians Formula Mineral Wear Diamond Lip Plumper Gloss"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product48 <- rbind(product48, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product48)

```


```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product49 <- data.frame()

for (page in 1:5) {
  link49 <- paste0("https://www.amazon.com.au/Kosas-Gloss-Plumping-Treatment-Unzipped/product-reviews/B09XJ93C8N/ref=cm_cr_dp_d_show_all_btm", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session49 <- bow(link49, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session49) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Kosas Wet Lip Oil Gloss | Juicy, Plumping Treatment"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product49 <- rbind(product49, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product49)

```


```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product50 <- data.frame()

for (page in 1:5) {
  link50 <- paste0("https://www.amazon.com.au/LOREAL-PARIS-LOr%C3%A9al-Infallible-Relentless/product-reviews/B00AQDPMRW/ref=cm_cr_dp_d_show_all_btm", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session50 <- bow(link50, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session50) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "L'OREAL PARIS Infallible 2Step Lipstick, Relentless Rouge"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product50 <- rbind(product50, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product50)


```

```{r}

all_products = data.frame();

all_products <- rbind(all_products, product1, product2, product3, product4, product5, product6, product7, product8, product9, product10, product11, product12, product13, product14, product15, product16, product16, product18, product19, product20, product21, product22, product23, product24, product25, product26, product27, product28, product29, product30, product31, product32, product33, product34, product35, product36, product37, product38, product39, product40, product41, product42, product43, product44, product45, product46, product47, product48, product49, product50)

#View(all_products)


write.csv(all_products,"all_products.csv")
```













